/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ApiPublicFinancialRouteImport } from './routes/api/public/financial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFinancialRoute = ApiPublicFinancialRouteImport.update({
  id: '/api/public/financial',
  path: '/api/public/financial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/calculator': typeof CalculatorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/report': typeof ReportRoute
  '/schemes': typeof SchemesRoute
  '/api/public/financial': typeof ApiPublicFinancialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/calculator': typeof CalculatorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/report': typeof ReportRoute
  '/schemes': typeof SchemesRoute
  '/api/public/financial': typeof ApiPublicFinancialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/calculator': typeof CalculatorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/report': typeof ReportRoute
  '/schemes': typeof SchemesRoute
  '/api/public/financial': typeof ApiPublicFinancialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/calculator'
    | '/how-it-works'
    | '/report'
    | '/schemes'
    | '/api/public/financial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/calculator'
    | '/how-it-works'
    | '/report'
    | '/schemes'
    | '/api/public/financial'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/calculator'
    | '/how-it-works'
    | '/report'
    | '/schemes'
    | '/api/public/financial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  CalculatorRoute: typeof CalculatorRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ReportRoute: typeof ReportRoute
  SchemesRoute: typeof SchemesRoute
  ApiPublicFinancialRoute: typeof ApiPublicFinancialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/financial': {
      id: '/api/public/financial'
      path: '/api/public/financial'
      fullPath: '/api/public/financial'
      preLoaderRoute: typeof ApiPublicFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  CalculatorRoute: CalculatorRoute,
  HowItWorksRoute: HowItWorksRoute,
  ReportRoute: ReportRoute,
  SchemesRoute: SchemesRoute,
  ApiPublicFinancialRoute: ApiPublicFinancialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
